[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[[bin]]
name = "aoc2022"
path = "src/timing.rs"

[dependencies]
array2d = "0.3.0"
evalexpr = "11.1.0"
itertools = "0.11.0"
pathfinding = "4.4.0"
