[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[[bin]]
name = "aoc2021"
path = "src/timing.rs"

[dependencies]
array2d = "0.2.1"
itertools = "0.10.1"